VNDK_28_ARM32 := vendor/vndk/vndk-28-arm32
VNDK_SP_28_ARM32 := vendor/vndk/vndk-sp-28-arm32
TARGET_SYSTEM_VNDK_OUT := system/lib/vndk-28
TARGET_SYSTEM_VNDK_SP_OUT := system/lib/vndk-sp-28

PRODUCT_COPY_FILES += \
	$(VNDK_28_ARM32)/android.frameworks.displayservice@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.frameworks.displayserver@1.0.so
	$(VNDK_28_ARM32)/android.frameworks.schedulerservice@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.frameworks.schedulerservice@1.0.so
	$(VNDK_28_ARM32)/android.frameworks.sensorservice@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/androud.frameworks.sensorservice@1.0.so
	$(VNDK_28_ARM32)/android.frameworks.vr.composer@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.frameworks.vr.composer@1.0.so
	$(VNDK_28_ARM32)/android.hardware.audio@2.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.audio@2.0.so
	$(VNDK_28_ARM32)/android.hardware.audio@4.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.audio@4.0.so
	$(VNDK_28_ARM32)/android.hardware.audio.common@2.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.audio.common@2.0.so
	$(VNDK_28_ARM32)/android.hardware.audio.common@2.0-util.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.audio.common@2.0-util.so
	$(VNDK_28_ARM32)/android.hardware.audio.common@4.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.audio.common@2.0-util.so
	$(VNDK_28_ARM32)/android.hardware.audio.common@4.0-util.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.audio.common@4.0-util.so
	$(VNDK_28_ARM32)/android.hardware.audio.common-util.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.audio.common-util.so
	$(VNDK_28_ARM32)/android.hardware.audio.effect@2.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.audio.effect@2.0.so
	$(VNDK_28_ARM32)/android.hardware.audio.effect@4.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.audio.effect@4.0.so
	$(VNDK_28_ARM32)/android.hardware.authsecret@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.authsecret@1.0.so
	$(VNDK_28_ARM32)/android.hardware.automotive.audiocontrol@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.automotive.audiocontrol@1.0.so
	$(VNDK_28_ARM32)/android.hardware.automotive.evs@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.automotive.evs@1.0.so
	$(VNDK_28_ARM32)/android.hardware.automotive.vehicle@2.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.automotive.vehicle@2.0.so
	$(VNDK_28_ARM32)/android.hardware.biometrics.fingerprint@2.1.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.biometrics.fingerprint@2.1.so
	$(VNDK_28_ARM32)/android.hardware.bluetooth@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.bluetooth@1.0.so
	$(VNDK_28_ARM32)/android.hardware.bluetooth.a2dp@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.bluetooth.a2dp@1.0.so
	$(VNDK_28_ARM32)/android.hardware.boot@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.boot@1.0.so
	$(VNDK_28_ARM32)/android.hardware.broadcastradio@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.broadcastradio@1.0.so
	$(VNDK_28_ARM32)/android.hardware.broadcastradio@1.1.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.broadcastradio@1.1.so
	$(VNDK_28_ARM32)/android.hardware.broadcastradio@2.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.broadcastradio@2.0.so
	$(VNDK_28_ARM32)/android.hardware.camera.common@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.camera.common@1.0.so
	$(VNDK_28_ARM32)/android.hardware.camera.device@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.camera.device@1.0.so
	$(VNDK_28_ARM32)/android.hardware.camera.device@3.2.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.camera.device@3.2.so
	$(VNDK_28_ARM32)/android.hardware.camera.device@3.3.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.camera.device@3.3.so
	$(VNDK_28_ARM32)/android.hardware.camera.device@3.4.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.camera.device@3.4.so
	$(VNDK_28_ARM32)/android.hardware.camera.metadata@3.2.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.camera.metadata@3.2.so
	$(VNDK_28_ARM32)/android.hardware.camera.metadata@3.3.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.camera.metadata@3.3.so
	$(VNDK_28_ARM32)/android.hardware.camera.provider@2.4.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.camera.provider@2.4.so
	$(VNDK_28_ARM32)/android.hardware.cas@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.cas@1.0.so
	$(VNDK_28_ARM32)/android.hardware.cas.native@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.cas.native@1.0.so
	$(VNDK_28_ARM32)/android.hardware.configstore@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.configstore@1.0.so
	$(VNDK_28_ARM32)/android.hardware.configstore@1.1.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.configstore@1.1.so
	$(VNDK_28_ARM32)/android.hardware.configstore-utils.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.configstore-utils.so
	$(VNDK_28_ARM32)/android.hardware.confirmationui@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.confirmationui@1.0.so
	$(VNDK_28_ARM32)/android.hardware.confirmationui-support-lib.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.confirmationui-support-lib.so
	$(VNDK_28_ARM32)/android.hardware.contexthub@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.contexthub@1.0.so
	$(VNDK_28_ARM32)/android.hardware.drm@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.drm@1.0.so
	$(VNDK_28_ARM32)/android.hardware.drm@1.1.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.drm@1.1.so
	$(VNDK_28_ARM32)/android.hardware.dumpstate@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.dumpstate@1.0.so
	$(VNDK_28_ARM32)/android.hardware.gatekeeper@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.gatekeeper@1.0.so
	$(VNDK_28_ARM32)/android.hardware.gnss@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.gnss@1.0.so
	$(VNDK_28_ARM32)/android.hardware.gnss@1.1.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.gnss@1.1.so
	$(VNDK_28_ARM32)/android.hardware.graphics.allocator@2.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.graphics.allocator@2.0.so
	$(VNDK_28_ARM32)/android.hardware.graphics.bufferqueue@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.graphics.bufferqueue@1.0.so
	$(VNDK_28_ARM32)/android.hardware.graphics.composer@2.1.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.graphics.composer@2.1.so
	$(VNDK_28_ARM32)/android.hardware.graphics.composer@2.2.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.graphics.composer@2.2.so
	$(VNDK_28_ARM32)/android.hardware.health@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.health@1.0.so
	$(VNDK_28_ARM32)/android.hardware.health@2.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.health@2.0.so
	$(VNDK_28_ARM32)/android.hardware.ir@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.ir@1.0.so
	$(VNDK_28_ARM32)/android.hardware.keymaster@3.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.keymaster@3.0.so
	$(VNDK_28_ARM32)/android.hardware.keymaster@4.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.keymaster@4.0.so
	$(VNDK_28_ARM32)/android.hardware.light@2.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.light@2.0.so
	$(VNDK_28_ARM32)/android.hardware.media@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.media@1.0.so
	$(VNDK_28_ARM32)/android.hardware.media.bufferpool@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.media.bufferpool@1.0.so
	$(VNDK_28_ARM32)/android.hardware.media.omx@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.media.omx@1.0.so
	$(VNDK_28_ARM32)/android.hardware.memtrack@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.memtrack@1.0.so
	$(VNDK_28_ARM32)/android.hardware.neuralnetworks@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.neuralnetworks@1.0.so
	$(VNDK_28_ARM32)/android.hardware.neuralnetworks@1.1.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.neuralnetworks@1.1.so
	$(VNDK_28_ARM32)/android.hardware.nfc@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.nfc@1.0.so
	$(VNDK_28_ARM32)/android.hardware.nfc@1.1.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.nfc@1.1.so
	$(VNDK_28_ARM32)/android.hardware.oemlock@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.oemlock@1.0.so
	$(VNDK_28_ARM32)/android.hardware.power@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.power@1.0.so
	$(VNDK_28_ARM32)/android.hardware.power@1.1.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.power@1.1.so
	$(VNDK_28_ARM32)/android.hardware.power@1.2.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.power@1.2.so
	$(VNDK_28_ARM32)/android.hardware.radio@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.radio@1.0.so
	$(VNDK_28_ARM32)/android.hardware.radio@1.1.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.radio@1.1.so
	$(VNDK_28_ARM32)/android.hardware.radio@1.2.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.radio@1.2.so
	$(VNDK_28_ARM32)/android.hardware.radio.config@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.radio.config@1.0.so
	$(VNDK_28_ARM32)/android.hardware.radio.deprecated@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.radio.deprecated@1.0.so
	$(VNDK_28_ARM32)/android.hardware.secure_element@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.secure_element@1.0.so
	$(VNDK_28_ARM32)/android.hardware.sensors@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.sensors@1.0.so
	$(VNDK_28_ARM32)/android.hardware.soundtrigger@2.0-core.so:$(TARGET_SYSTEM_VNDK_OUT)/androud.hardware.soundtrigger@2.0-core.so
	$(VNDK_28_ARM32)/android.hardware.soundtrigger@2.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.soundtrigger@2.0.so
	$(VNDK_28_ARM32)/android.hardware.soundtrigger@2.1.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.soundtrigger@2.1.so
	$(VNDK_28_ARM32)/android.hardware.tetheroffload.config@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.tetheroffload.config@1.0.so
	$(VNDK_28_ARM32)/android.hardware.tetheroffload.control@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.tetheroffload.control@1.0.so
	$(VNDK_28_ARM32)/android.hardware.thermal@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.thermal@1.0.so
	$(VNDK_28_ARM32)/android.hardware.thermal@1.1.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.thermal@1.1.so
	$(VNDK_28_ARM32)/android.hardware.tv.cec@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.tv.cec@1.0.so
	$(VNDK_28_ARM32)/android.hardware.tv.input@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.tv.input@1.0.so
	$(VNDK_28_ARM32)/android.hardware.usb@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.usb@1.0.so
	$(VNDK_28_ARM32)/android.hardware.usb@1.1.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.usb@1.1.so
	$(VNDK_28_ARM32)/android.hardware.usb.gadget@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.usb.gadget@1.0.so
	$(VNDK_28_ARM32)/android.hardware.vibrator@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.vibrator@1.0.so
	$(VNDK_28_ARM32)/android.hardware.vibrator@1.1.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.vibrator@1.1.so
	$(VNDK_28_ARM32)/android.hardware.vibrator@1.2.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.vibrator@1.2.so
	$(VNDK_28_ARM32)/android.hardware.vr@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.vr@1.0.so
	$(VNDK_28_ARM32)/android.hardware.weaver@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.weaver@1.0.so
	$(VNDK_28_ARM32)/android.hardware.wifi@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.wifi@1.0.so
	$(VNDK_28_ARM32)/android.hardware.wifi@1.1.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.wifi@1.1.so
	$(VNDK_28_ARM32)/android.hardware.wifi@1.2.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.wifi@1.2.so
	$(VNDK_28_ARM32)/android.hardware.wifi.hostapd@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.wifi.hostapd@1.0.so
	$(VNDK_28_ARM32)/android.hardware.wifi.offload@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.wifi.offload@1.0.so
	$(VNDK_28_ARM32)/android.hardware.wifi.supplicant@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.wifi.supplicant@1.0.so
	$(VNDK_28_ARM32)/android.hardware.wifi.supplicant@1.1.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hardware.wifi.supplicant@1.1.so
	$(VNDK_28_ARM32)/android.hidl.allocator@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hidl.allocator@1.0.so
	$(VNDK_28_ARM32)/android.hidl.base@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hidl.base@1.0.so
	$(VNDK_28_ARM32)/android.hidl.memory.block@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hidl.memory.block@1.0.so
	$(VNDK_28_ARM32)/android.hidl.token@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hidl.token@1.0.so
	$(VNDK_28_ARM32)/android.hidl.token@1.0-utils.so:$(TARGET_SYSTEM_VNDK_OUT)/android.hidl.token@1.0-utils.so
	$(VNDK_28_ARM32)/android.system.net.netd@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.system.net.netd@1.0.so
	$(VNDK_28_ARM32)/android.system.net.netd@1.1.so:$(TARGET_SYSTEM_VNDK_OUT)/android.system.net.netd@1.1.so
	$(VNDK_28_ARM32)/android.system.wifi.keystore@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/android.system.wifi.keystore@1.0.so
	$(VNDK_28_ARM32)/com.qualcomm.qti.wifidisplayhal@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/com.qualcomm.qti.wifidisplayhal@1.0.so
	$(VNDK_28_ARM32)/libadf.so:$(TARGET_SYSTEM_VNDK_OUT)/libadf.so
	$(VNDK_28_ARM32)/libandroidicu.so:$(TARGET_SYSTEM_VNDK_OUT)/libandroidicu.so
	$(VNDK_28_ARM32)/libaudioroute.so:$(TARGET_SYSTEM_VNDK_OUT)/libaudioroute.so
	$(VNDK_28_ARM32)/libaudioutils.so:$(TARGET_SYSTEM_VNDK_OUT)/libaudioutils.so
	$(VNDK_28_ARM32)/libbinder.so:$(TARGET_SYSTEM_VNDK_OUT)/libbinder.so
	$(VNDK_28_ARM32)/libbufferhubqueue.so:$(TARGET_SYSTEM_VNDK_OUT)/libbufferhubqueue.so
	$(VNDK_28_ARM32)/libcamera_client.so:$(TARGET_SYSTEM_VNDK_OUT)/libcamera_client.so
	$(VNDK_28_ARM32)/libcamera_metadata.so:$(TARGET_SYSTEM_VNDK_OUT)/libcamera_metadata.so
	$(VNDK_28_ARM32)/libcap.so:$(TARGET_SYSTEM_VNDK_OUT)/libcap.so
	$(VNDK_28_ARM32)/libclang_rt.ubsan_standalone-arm-android.so:$(TARGET_SYSTEM_VNDK_OUT)/libclang_rt.ubsan_standalone-arm-android.so
	$(VNDK_28_ARM32)/libcn-cbor.so:$(TARGET_SYSTEM_VNDK_OUT)/libcn-cbor.so
	$(VNDK_28_ARM32)/libcrypto.so:$(TARGET_SYSTEM_VNDK_OUT)/libcrypto.so
	$(VNDK_28_ARM32)/libcrypto_utils.so:$(TARGET_SYSTEM_VNDK_OUT)/libcrypto_utils.so
	$(VNDK_28_ARM32)/libcurl.so:$(TARGET_SYSTEM_VNDK_OUT)/libcurl.so
	$(VNDK_28_ARM32)/libdiskconfig.so:$(TARGET_SYSTEM_VNDK_OUT)/libdiskconfig.so
	$(VNDK_28_ARM32)/libdrm.so:$(TARGET_SYSTEM_VNDK_OUT)/libdrm.so
	$(VNDK_28_ARM32)/libdumpstateutil.so:$(TARGET_SYSTEM_VNDK_OUT)/libdumpstateutil.so
	$(VNDK_28_ARM32)/libeffectsconfig.so:$(TARGET_SYSTEM_VNDK_OUT)/libeffectsconfig.so
	$(VNDK_28_ARM32)/libevent.so:$(TARGET_SYSTEM_VNDK_OUT)/libevent.so
	$(VNDK_28_ARM32)/libexif.so:$(TARGET_SYSTEM_VNDK_OUT)/libexif.so
	$(VNDK_28_ARM32)/libexpat.so:$(TARGET_SYSTEM_VNDK_OUT)/libexpat.so
	$(VNDK_28_ARM32)/libfmq.so:$(TARGET_SYSTEM_VNDK_OUT)/libfmq.so
	$(VNDK_28_ARM32)/libgatekeeper.so:$(TARGET_SYSTEM_VNDK_OUT)/libgatekeeper.so
	$(VNDK_28_ARM32)/libgui.so:$(TARGET_SYSTEM_VNDK_OUT)/libgui.so
	$(VNDK_28_ARM32)/libhardware_legacy.so:$(TARGET_SYSTEM_VNDK_OUT)/libhardware_legacy.so
	$(VNDK_28_ARM32)/libhidlallocatorutils.so:$(TARGET_SYSTEM_VNDK_OUT)/libhidlallocatorutils.so
	$(VNDK_28_ARM32)/libhidlcache.so:$(TARGET_SYSTEM_VNDK_OUT)/libhidlcache.so
	$(VNDK_28_ARM32)/libicui18n.so:$(TARGET_SYSTEM_VNDK_OUT)/libicui18n.so
	$(VNDK_28_ARM32)/libicuuc.so:$(TARGET_SYSTEM_VNDK_OUT)/libicuuc.so
	$(VNDK_28_ARM32)/libjpeg.so:$(TARGET_SYSTEM_VNDK_OUT)/libjpeg.so
	$(VNDK_28_ARM32)/libkeymaster_messages.so:$(TARGET_SYSTEM_VNDK_OUT)/libkeymaster_messages.so
	$(VNDK_28_ARM32)/libkeymaster_portable.so:$(TARGET_SYSTEM_VNDK_OUT)/libkeymaster_portable.so
	$(VNDK_28_ARM32)/libkeystore_binder.so:$(TARGET_SYSTEM_VNDK_OUT)/libkeystore_binder.so
	$(VNDK_28_ARM32)/libldacBT_abr.so:$(TARGET_SYSTEM_VNDK_OUT)/libldacBT_abr.so
	$(VNDK_28_ARM32)/libldacBT_enc.so:$(TARGET_SYSTEM_VNDK_OUT)/libldacBT_enc.so
	$(VNDK_28_ARM32)/liblz4.so:$(TARGET_SYSTEM_VNDK_OUT)/liblz4.so
	$(VNDK_28_ARM32)/libmedia_helper.so:$(TARGET_SYSTEM_VNDK_OUT)libmedia_helper.so
	$(VNDK_28_ARM32)/libmedia_omx.so:$(TARGET_SYSTEM_VNDK_OUT)/libmedia_omx.so
	$(VNDK_28_ARM32)/libmemtrack.so:$(TARGET_SYSTEM_VNDK_OUT)/libmemtrack.so
	$(VNDK_28_ARM32)/libminijail.so:$(TARGET_SYSTEM_VNDK_OUT)/libminijail.so
	$(VNDK_28_ARM32)/libmkbootimg_abi_check.so:$(TARGET_SYSTEM_VNDK_OUT)/libmkbootimg_abi_check.so
	$(VNDK_28_ARM32)/libnetutils.so:$(TARGET_SYSTEM_VNDK_OUT)/libnetutils.so
	$(VNDK_28_ARM32)/libnl.so:$(TARGET_SYSTEM_VNDK_OUT)/libnl.so
	$(VNDK_28_ARM32)/libopus.so:$(TARGET_SYSTEM_VNDK_OUT)/libopus.so
	$(VNDK_28_ARM32)/libpagemap.so:$(TARGET_SYSTEM_VNDK_OUT)/libpagemap.so
	$(VNDK_28_ARM32)/libpcre2.so:$(TARGET_SYSTEM_VNDK_OUT)/libpcre2.so
	$(VNDK_28_ARM32)/libpiex.so:$(TARGET_SYSTEM_VNDK_OUT)/libpiex.so
	$(VNDK_28_ARM32)/libpng.so:$(TARGET_SYSTEM_VNDK_OUT)/libpng.so
	$(VNDK_28_ARM32)/libpower.so:$(TARGET_SYSTEM_VNDK_OUT)/libpower.so
	$(VNDK_28_ARM32)/libprocinfo.so:$(TARGET_SYSTEM_VNDK_OUT)/libprocinfo.so
	$(VNDK_28_ARM32)/libprotobuf-cpp-full.so:$(TARGET_SYSTEM_VNDK_OUT)/libprotobuf-cpp-full.so
	$(VNDK_28_ARM32)/libprotobuf-cpp-lite.so:$(TARGET_SYSTEM_VNDK_OUT)/libprotobuf-cpp-lite.so
	$(VNDK_28_ARM32)/libpuresoftkeymasterdevice.so:$(TARGET_SYSTEM_VNDK_OUT)/libpuresoftkeymasterdevice.so
	$(VNDK_28_ARM32)/libradio_metadata.so:$(TARGET_SYSTEM_VNDK_OUT)/libradio_metadata.so
	$(VNDK_28_ARM32)/libselinux.so:$(TARGET_SYSTEM_VNDK_OUT)/libselinux.so
	$(VNDK_28_ARM32)/libsoftkeymasterdevice.so:$(TARGET_SYSTEM_VNDK_OUT)/libsoftkeymasterdevice.so
	$(VNDK_28_ARM32)/libspeexresampler.so:$(TARGET_SYSTEM_VNDK_OUT)/libspeexresampler.so
	$(VNDK_28_ARM32)/libsqlite.so:$(TARGET_SYSTEM_VNDK_OUT)/libsqlite.so
	$(VNDK_28_ARM32)/libssl.so:$(TARGET_SYSTEM_VNDK_OUT)/libssl.so
	$(VNDK_28_ARM32)/libstagefright_amrnb_common.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_amrnb_common.so
	$(VNDK_28_ARM32)/libstagefright_bufferqueue_helper.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_bufferqueue_helper.so
	$(VNDK_28_ARM32)/libstagefright_enc_common.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_enc_common.so
	$(VNDK_28_ARM32)/libstagefright_flacdec.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_flacdec.so
	$(VNDK_28_ARM32)/libstagefright_foundation.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_foundation.so
	$(VNDK_28_ARM32)/libstagefright_omx.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_omx.so
	$(VNDK_28_ARM32)/libstagefright_omx_utils.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_omx_utils.so
	$(VNDK_28_ARM32)/libstagefright_soft_aacdec.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_aacdec.so
	$(VNDK_28_ARM32)/libstagefright_soft_aacenc.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_aacenc.so
	$(VNDK_28_ARM32)/libstagefright_soft_amrdec.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_amrdec.so
	$(VNDK_28_ARM32)/libstagefright_soft_amrnbenc.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_amrnbenc.so
	$(VNDK_28_ARM32)/libstagefright_soft_amrwbenc.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_amrwbenc.so
	$(VNDK_28_ARM32)/libstagefright_soft_avcdec.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_avcdec.so
	$(VNDK_28_ARM32)/libstagefright_soft_avcenc.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_avcenc.so
	$(VNDK_28_ARM32)/libstagefright_soft_flacdec.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_flacdec.so
	$(VNDK_28_ARM32)/libstagefright_soft_flacenc.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_flacenc.so
	$(VNDK_28_ARM32)/libstagefright_soft_g711dec.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_g711dec.so
	$(VNDK_28_ARM32)/libstagefright_soft_gsmdec.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_gsmdec.so
	$(VNDK_28_ARM32)/libstagefright_soft_hevcdec.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_hevcdec.so
	$(VNDK_28_ARM32)/libstagefright_soft_mp3dec.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_mp3dec.so
	$(VNDK_28_ARM32)/libstagefright_soft_mpeg2dec.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_mpeg2dec.so
	$(VNDK_28_ARM32)/libstagefright_soft_mpeg4dec.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_mpeg4dec.so
	$(VNDK_28_ARM32)/libstagefright_soft_mpeg4enc.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_mpeg4enc.so
	$(VNDK_28_ARM32)/libstagefright_soft_opusdec.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_opusdec.so
	$(VNDK_28_ARM32)/libstagefright_soft_rawdec.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_rawdec.so
	$(VNDK_28_ARM32)/libstagefright_soft_vorbisdec.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_vorbisdec.so
	$(VNDK_28_ARM32)/libstagefright_soft_vpxdec.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_vpxdec.so
	$(VNDK_28_ARM32)/libstagefright_soft_vpxenc.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_soft_vpxenc.so
	$(VNDK_28_ARM32)/libstagefright_xmlparser.so:$(TARGET_SYSTEM_VNDK_OUT)/libstagefright_xmlparser.so
	$(VNDK_28_ARM32)/libstdc++.so:$(TARGET_SYSTEM_VNDK_OUT)/libstdc++.so
	$(VNDK_28_ARM32)/libsuspend.so:$(TARGET_SYSTEM_VNDK_OUT)/libsuspend.so
	$(VNDK_28_ARM32)/libsysutils.so:$(TARGET_SYSTEM_VNDK_OUT)/libsysutils.so
	$(VNDK_28_ARM32)/libtinyalsa.so:$(TARGET_SYSTEM_VNDK_OUT)/libtinyalsa.so
	$(VNDK_28_ARM32)/libtinyxml2.so:$(TARGET_SYSTEM_VNDK_OUT)/libtinyxml2.so
	$(VNDK_28_ARM32)/libui.so:$(TARGET_SYSTEM_VNDK_OUT)/libui.so
	$(VNDK_28_ARM32)/libusbhost.so:$(TARGET_SYSTEM_VNDK_OUT)/libusbhost.so
	$(VNDK_28_ARM32)/libvixl-arm64.so:$(TARGET_SYSTEM_VNDK_OUT)/libvixl-arm64.so
	$(VNDK_28_ARM32)/libvixl-arm.so:$(TARGET_SYSTEM_VNDK_OUT)/libvixl-arm.so
	$(VNDK_28_ARM32)/libvorbisidec.so:$(TARGET_SYSTEM_VNDK_OUT)/libvorbisidec.so
	$(VNDK_28_ARM32)/libwifi-system-iface.so:$(TARGET_SYSTEM_VNDK_OUT)/libwifi-system-iface.so
	$(VNDK_28_ARM32)/libxml2.so:$(TARGET_SYSTEM_VNDK_OUT)/libxml2.so
	$(VNDK_28_ARM32)/libyuv.so:$(TARGET_SYSTEM_VNDK_OUT)/libyuv.so
	$(VNDK_28_ARM32)/libziparchive.so:$(TARGET_SYSTEM_VNDK_OUT)/libziparchive.so
	$(VNDK_28_ARM32)/vendor.display.config@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/vendor.display.config@1.0.so
	$(VNDK_28_ARM32)/vendor.display.config@1.1.so:$(TARGET_SYSTEM_VNDK_OUT)/vendor.display.config@1.1.so
	$(VNDK_28_ARM32)/vendor.qti.hardware.camera.device@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/vendor.qti.hardware.camera.device@1.0.so
	$(VNDK_28_ARM32)/vendor.qti.hardware.tui_comm@1.0.so:$(TARGET_SYSTEM_VNDK_OUT)/vendor.qti.hardware.tui_comm@1.0.so

PRODUCT_COPY_FILES += \
	$(VNDK_SP_28_ARM32)/android.hardware.graphics.common@1.0.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/android.hardware.graphics.common@1.0.so
	$(VNDK_SP_28_ARM32)/android.hardware.graphics.common@1.1.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/android.hardware.graphics.common@1.1.so
	$(VNDK_SP_28_ARM32)/android.hardware.graphics.mapper@2.0.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/android.hardware.graphics.mapper@2.0.so
	$(VNDK_SP_28_ARM32)/android.hardware.graphics.mapper@2.1.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/android.hardware.graphics.mapper@2.1.so
	$(VNDK_SP_28_ARM32)/android.hardware.renderscript@1.0.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/android.hardware.renderscript@1.0.so
	$(VNDK_SP_28_ARM32)/android.hidl.memory@1.0.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/android.hidl.memory@1.0.so
	$(VNDK_SP_28_ARM32)/android.hidl.memory.token@1.0.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/android.hidl.memory.token@1.0.so
	$(VNDK_SP_28_ARM32)/libbacktrace.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libbacktrace.so
	$(VNDK_SP_28_ARM32)/libbase.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libbase.so
	$(VNDK_SP_28_ARM32)/libbcinfo.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libbcinfo.so
	$(VNDK_SP_28_ARM32)/libblas.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libblas.so
	$(VNDK_SP_28_ARM32)/libcompiler_rt.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libcompiler_rt.so
	$(VNDK_SP_28_ARM32)/libc++.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libc++.so
	$(VNDK_SP_28_ARM32)/libcutils.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libcutils.so
	$(VNDK_SP_28_ARM32)/libhardware.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libhardware.so
	$(VNDK_SP_28_ARM32)/libhidlbase.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libhidlbase.so
	$(VNDK_SP_28_ARM32)/libhidlmemory.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libhidlmemory.so
	$(VNDK_SP_28_ARM32)/libhidltransport.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libhidltransport.so
	$(VNDK_SP_28_ARM32)/libhwbinder_noltopgo.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libhwbinder_noltopgo.so
	$(VNDK_SP_28_ARM32)/libhwbinder.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libhwbinder.so
	$(VNDK_SP_28_ARM32)/libion.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libion.so
	$(VNDK_SP_28_ARM32)/liblzma.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/liblzma.so
	$(VNDK_SP_28_ARM32)/libRSCpuRef.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libRSCpuRef.so
	$(VNDK_SP_28_ARM32)/libRSDriver.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libRSDriver.so
	$(VNDK_SP_28_ARM32)/libRS_internal.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libRS_internal.so
	$(VNDK_SP_28_ARM32)/libunwind.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libunwind.so
	$(VNDK_SP_28_ARM32)/libunwindstack.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libunwindstack.so
	$(VNDK_SP_28_ARM32)/libutils.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/libutils.so
	$(VNDK_SP_28_ARM32)/hw/android.hidl.memory@1.0-impl.so:$(TARGET_SYSTEM_VNDK_SP_OUT)/hw/android.hidl.memory@1.0-impl.so

PRODUCT_COPY_FILES += \
	vendor/vndk/moreP/vndk-28-arm32/libandroid.so:system/lib/vndk-28/libandroid.so
	vendor/vndk/moreP/vndk-28-arm32/libhwui.so:system/lib/vndk-28/libhwui.so
